### ISSUE TITLE
Can you simplify the code ?

### ISSUE THREAD

**Issue by t-h2o** [0xCAF3D0OD/dynamic_library#4]
The goal of this repository is to explain how create a dynamic library not to show a sorting algorithm.

**Comment by 0xCAF3D0OD** [comment]
It was a tutorial i follow it.

**Comment by t-h2o** [comment]
Great !
We use [**obscurantism**](https://en.wikipedia.org/wiki/Obscurantism) !
So much people will not be able to understand...
